In [11]:
import numpy as np

ar1=np.array([10,20,30,40,50])
print(arr)

[45 67 89 90 76]


In [14]:
arr2=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr2)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [15]:
arr3=np.zeros((2,2))
print(arr3)

[[0. 0.]
 [0. 0.]]


In [17]:
arr4=np.ones((2,3))
print(arr4)


[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
arr5=np.random.randint(1,20,5)
print(arr5)

[ 6  6 16 15 19]


In [19]:
arr4=np.random.randint(1,30,4).reshape(-1,2)
print(arr4)

[[ 6 22]
 [ 8 28]]


In [20]:
print(arr[1:4])


[67 89 90]


In [21]:
print(arr2.shape)

(3, 3)


In [22]:
print(arr4.T)

[[ 6  8]
 [22 28]]


In [23]:
print(np.mean(arr))


73.4


In [ ]:
print(np.median(arr))

In [ ]:
import numpy as np
from scipy import stats
arra=np.array([10,20,40,40,20])
print(stats.mode(arra))

In [ ]:
print(np.var(arr))

In [ ]:
print(np.std(arr))

In [ ]:
ar1=np.array([23,56,12,90,34,18,10])
print(np.sort(ar1))

In [ ]:
ar2=np.array([[12,89,34],[23,49,29],[67,89,30]])
print(ar2)

In [ ]:
print(np.sort(ar2,axis=0))

In [ ]:
print(np.sort(ar2,axis=1))

In [ ]:
ar3=np.array([[12,90,34],[25,78,90],[23,12,10]])
print(ar3)

In [ ]:
mat_mul=np.array(ar2*ar3)
print(mat_mul)

In [ ]:
mat_add=np.array(ar2+ar3)
print(mat_add)

In [ ]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
concat=np.concatenate((a1,a2))
print(concat)

In [ ]:
print(np.unique(concat))

In [ ]:
print(np.linspace(1,10,5))

In [ ]:
print(np.identity(3))

In [ ]:
print(np.eye(3,3))

In [ ]:
data=np.array([12,38,90,89,23,10,4,76])
print(np.argmin(data))

In [ ]:
print(data[6])

In [ ]:
print(np.argmax(data))

In [ ]:
print(data[2])

In [ ]:
print(np.where(data>=40))
# to get actual values instead of index
print(data[data>=40])

In [ ]:
print(np.cumsum(data))

In [ ]:
print(np.corrcoef(a1,a2))
# +1 = strong  positive correlation
#-1 = strong negative correlation

In [ ]:
new_data=np.arange(1,11,1)
print(new_data)

In [ ]:
np.save("new_data.npy",new_data)
loaded=np.load("new_data.npy")
print(loaded)