In [2]:
import numpy as np

marks = np.array([45, 67, 89, 90, 76])

print("First 3 Marks:", marks[:3])
print("Last 2 Marks:", marks[-2:])

marks = marks + 5
print("Updated Marks:", marks)

First 3 Marks: [45 67 89]
Last 2 Marks: [90 76]
Updated Marks: [50 72 94 95 81]


In [3]:
import numpy as np

zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
identity = np.eye(4)

print("Zeros Matrix:")
print(zeros)

print("Ones Matrix:")
print(ones)

print("Identity Matrix:")
print(identity)

Zeros Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
import numpy as np

decimal = np.random.rand(5)
integers = np.random.randint(1, 51, 10)

print("Random Decimal Numbers:", decimal)
print("Random Integers:", integers)

Random Decimal Numbers: [0.25178386 0.81414543 0.46001101 0.81665497 0.33053791]
Random Integers: [18  5 37 42 49 31 18 36 29 33]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = A @ B
transpose = A.T

print("Matrix Multiplication:")
print(result)

print("Transpose of A:")
print(transpose)

Matrix Multiplication:
[[19 22]
 [43 50]]
Transpose of A:
[[1 3]
 [2 4]]


In [7]:
import numpy as np

marks = np.array([78, 85, 90, 62, 88])

print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))

Mean: 80.6
Median: 85.0
Standard Deviation: 10.150862032359617


In [8]:
import numpy as np

arr = np.array([5, 2, 8, 2, 9, 1, 5])

print("Sorted Array:", np.sort(arr))
print("Unique Elements:", np.unique(arr))

Sorted Array: [1 2 2 5 5 8 9]
Unique Elements: [1 2 5 8 9]


In [9]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

combined = np.concatenate((a, b))
values = np.linspace(0, 10, 5)

print("Concatenated Array:", combined)
print("Linspace Values:", values)

Concatenated Array: [1 2 3 4 5 6]
Linspace Values: [ 0.   2.5  5.   7.5 10. ]


In [10]:
import numpy as np

arr = np.array([23, 45, 12, 67, 34])

print("Argmax Index:", np.argmax(arr))
print("Argmin Index:", np.argmin(arr))

result = np.where(arr > 30, arr, 0)

print("Values Greater Than 30:", arr[arr > 30])

Argmax Index: 3
Argmin Index: 2
Values Greater Than 30: [45 67 34]


In [11]:
import numpy as np

# Task 10 - Sales Analysis Project

# Part 1 - Cumulative Sum
sales = np.array([100, 200, 150, 300])

cumulative = np.cumsum(sales)

print("Cumulative Sum:", cumulative)


# Part 2 - Correlation Coefficient
hours = np.array([1, 2, 3, 4, 5])
marks = np.array([20, 40, 50, 70, 90])

correlation = np.corrcoef(hours, marks)

print("Correlation Coefficient:", correlation[0, 1])


# Part 3 - Save and Load
arr = np.array([10, 20, 30, 40])

np.save("numbers.npy", arr)

loaded = np.load("numbers.npy")

print("Loaded Array:", loaded)

Cumulative Sum: [100 300 450 750]
Correlation Coefficient: 0.9948497511671097
Loaded Array: [10 20 30 40]
